### ISSUE TITLE
DataMut is not implemented for mutable array subslices, AddAssign

### ISSUE THREAD

**Issue by comath** [rust-ndarray/ndarray#822] opened 2020-06-04 00:15 UTC
I'm trying to create a data matrix with some artificial data, so I made a mutable zeroed out `Array2`, and try to create the data with `AddAssign`:

```Rust
let mut output: Array2<f64> = Array2::zeros(Ix2(num_samples as usize, dim));

    for j in 0..(num_samples as usize) {
        let mut output_slice: ArrayViewMut1<f64> = output.slice_mut(s![j, ..]);
        for i in 0..len {
            let k: usize = direction_dist.sample(&mut rng);
            let direction: ArrayView1<f64> = directions.as_array().slice(s![i,k, ..]);
            output_slice += direction;
        }
    }
```

There are a few related `AddAssign` implementations that show up in the errors, but the relevant one seems to be:
```
error[E0277]: the trait bound `ndarray::ViewRepr<&f64>: ndarray::data_traits::DataMut` is not satisfied
  --> src/lib.rs:25:26
   |
25 |             output_slice += direction;
   |                          ^^ the trait `ndarray::data_traits::DataMut` is not implemented for `ndarray::ViewRepr<&f64>`
   |
   = help: the following implementations were found:
             <ndarray::ViewRepr<&'a mut A> as ndarray::data_traits::DataMut>
   = note: required because of the requirements on the impl of `std::ops::AddAssign` for `ndarray::ArrayBase<ndarray::ViewRepr<&f64>, ndarray::dimension::dim::Dim<[usize; 1]>>`
   = note: required because of the requirements on the impl of `std::ops::AddAssign<ndarray::ArrayBase<ndarray::ViewRepr<&f64>, ndarray::dimension::dim::Dim<[usize; 1]>>>` for `ndarray::ArrayBase<ndarray::ViewRepr<&mut f64>, ndarray::dimension::dim::Dim<[usize; 1]>>`
```

To me, I have a mutable slice, I should be able to add-assign to this. I've tried this with `index_axis` and `index_axis_mut` too. 
As far as I can tell, it's because the second `direction` slice is not mutable, and thus not of the exact same type as the modifiable slice. The trait [documentation](https://docs.rs/ndarray/0.13.1/ndarray/struct.ArrayBase.html#impl-AddAssign%3C%26%27a%20ArrayBase%3CS2%2C%20E%3E%3E) seems to indicate it's this restrictive.

The full implementation is here: https://github.com/StellaAthena/fractal-ml/blob/rust_extension/src/lib.rs#L22-L25

**Comment by jturner314** [comment] 2020-06-04 01:35
Yeah, the set of implementations of arithmetic operations is somewhat confusing, and the error messages are sometimes misleading for arithmetic operations.

In this case, we want to perform an in-place arithmetic operation with two arrays, and the relevant implementation requires the right-hand-side to be a reference to an array. (This is the [`C @= &A` case in the docs](https://docs.rs/ndarray/0.13.1/ndarray/struct.ArrayBase.html#binary-operators-with-two-arrays).) In other words, the solution is to change

```rust
            output_slice += direction;
```

to

```rust
            output_slice += &direction;
```

By the way, you were correct that the relevant implementation is [this one](https://docs.rs/ndarray/0.13.1/ndarray/struct.ArrayBase.html#impl-AddAssign%3C%26%27a%20ArrayBase%3CS2%2C%20E%3E%3E). However, the issue is not mutability, but rather that `direction` is of type `ArrayView1<'_, f64>`, while the right-hand-side needs to be a reference to an array, e.g. `&ArrayView1<'_, f64>`. (See the `&'a ArrayBase<S2, E>` in `AddAssign<&'a ArrayBase<S2, E>>`. The type parameter of the `AddAssign` trait is the type of the right-hand-side; it's the `Rhs` parameter visible if you click "Show declaration" for the [docs for `AddAssign`](https://doc.rust-lang.org/stable/core/ops/trait.AddAssign.html).)

There's been some work to implement the arithmetic operators for more cases (so that, for example, an ampersand wouldn't be necessary in this case), but it hasn't been completed/merged yet.

**Closed** 2020-06-13 03:52 UTC
Labels: question
